# SPDX-License-Identifier: GPL-2.0

targets += $(addprefix ../../../, $(kapi)/sysreg-gen-defs.h)

kapi:   $(kapi)/sysreg-gen-defs.h

quiet_cmd_gen_sysreg = GEN     $@
      cmd_gen_sysreg = mkdir -p $(dir $@); $(AWK) -f $(real-prereqs) > $@

$(kapi)/sysreg-gen-defs.h: $(srctree)/arch/arm64/tools/gen-sysreg.awk $(srctree)/arch/arm64/tools/sysreg FORCE
	$(call if_changed,gen_sysreg)

