# SPDX-License-Identifier: GPL-2.0
#
# Extracts ARM64 marked sections to .inc files that are included by main source
# files

# List of ARM64 C files to extract
ARM64_CFILES := \
	arm.c \
	guest.c \
	reset.c \
	handle_exit.c \
	mmio.c \

quiet_cmd_extract_inc = GEN     $@
      cmd_extract_inc = mkdir -p $(dir $@); \
                        $(AWK) -f $(src)/copy-arm64c.awk $< > $@ || \
                        { echo "Error: No ARM64_S390_COMMON markers in $<" >&2; rm -f $@; exit 1; }

$(obj)/generated/%.inc: $(srctree)/arch/arm64/kvm/%.c $(src)/copy-arm64c.awk FORCE
	$(call if_changed,extract_inc)

ARM64_INC_FILES := $(foreach cfile,$(ARM64_CFILES),generated/$(basename $(cfile)).inc)

targets += $(ARM64_INC_FILES)
clean-files += generated/*.inc

$(addprefix $(obj)/,$(kvm-arm64-obj)): $(addprefix $(obj)/,$(ARM64_INC_FILES))

$(foreach cfile,$(basename $(ARM64_CFILES)),\
	$(eval $(obj)/$(cfile).o: $(obj)/generated/$(cfile).inc))
